apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-staging
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/YOUR-USERNAME/gitops-lbm-cluster-01.git' # replace after pushing
    targetRevision: main
    path: clusters/staging
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
